In [24]:
from pathlib import Path
import re
import pandas as pd
import numpy as np

In [2]:
kaggle_train = pd.read_csv(Path("./data/train.csv"))
kaggle_test = pd.read_csv(Path("./data/test.csv"))
ames = pd.read_csv(Path("./data/ames.csv"))

In [67]:
numeric_cols = list(kaggle_train.select_dtypes(np.number).columns)
numeric_cols

['Kaggle_ID',
 'MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SalePrice']

In [70]:
kaggle_train["1stFlrSF"]

0        856
1       1262
2        920
3        961
4       1145
5        796
6       1694
7       1107
8       1022
9       1077
10      1040
11      1182
12       912
13      1494
14      1253
15       854
16      1004
17      1296
18      1114
19      1339
20      1158
21      1108
22      1795
23      1060
24      1060
25      1600
26       900
27      1704
28      1600
29       520
        ...
1430     734
1431     958
1432     968
1433     962
1434    1126
1435    1537
1436     864
1437    1932
1438    1236
1439    1040
1440    1423
1441     848
1442    1026
1443     952
1444    1422
1445     913
1446    1188
1447    1220
1448     796
1449     630
1450     896
1451    1578
1452    1072
1453    1140
1454    1221
1455     953
1456    2073
1457    1188
1458    1078
1459    1256
Name: 1stFlrSF, Length: 1460, dtype: int64

In [69]:
kaggle_train[numeric_cols] = kaggle_train[numeric_cols].astype(int)

ValueError: Cannot convert non-finite values (NA or inf) to integer

In [4]:
ames.head()

,Order,PID,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,Lot.Shape,Land.Contour,...,Pool.Area,Pool.QC,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [20]:
kaggle_train.rename(columns = {"Id":"Kaggle_ID"}, inplace= True)
kaggle_train.head()

,Kaggle_ID,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [31]:
amesMod = ames.drop(columns=["PID"]).rename(columns = {"Order" : "Ames_ID"})
amesMod.columns = [re.sub("(^X)|([.])","",i) for i in amesMod.columns]
amesMod.head()

,Ames_ID,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [32]:
amesMod.columns

Index(['Ames_ID', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [13]:
kaggle_train.SalePrice.value_counts()

140000    20
135000    17
145000    14
155000    14
190000    13
110000    13
160000    12
115000    12
139000    11
130000    11
125000    10
143000    10
185000    10
180000    10
144000    10
175000     9
147000     9
100000     9
127000     9
165000     8
176000     8
170000     8
129000     8
230000     8
250000     8
200000     8
141000     8
215000     8
148000     7
173000     7
          ..
64500      1
326000     1
277500     1
259000     1
254900     1
131400     1
181134     1
142953     1
245350     1
121600     1
337500     1
228950     1
274000     1
317000     1
154500     1
52000      1
107400     1
218000     1
104000     1
68500      1
94000      1
466500     1
410000     1
437154     1
219210     1
84900      1
424870     1
415298     1
62383      1
34900      1
Name: SalePrice, Length: 663, dtype: int64

In [37]:
allCols = list(kaggle_train.drop(columns="Kaggle_ID").columns)
print(allCols)

['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice']

In [115]:
kaggle_train.RoofMatl.value_counts()

CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
ClyTile       1
Membran       1
Metal         1
Roll          1
Name: RoofMatl, dtype: int64

In [84]:
def checkCols(x,colnames):
    @np.vectorize
    def compare(x,y):
        try: 
            return np.equal(x,y)
        except:
            return x == y
    return np.all([compare(x[i+"_x"],x[i+"_y"]) for i in colnames])

In [79]:

    
print(compare(1.0,1))

True

In [71]:
np.equal(1.0,1)

True

In [59]:
kaggle_train.select_dtypes(np.number)

,Kaggle_ID,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000
5,6,50,85.0,14115,5,5,1993,1995,0.0,732,...,40,30,0,320,0,0,700,10,2009,143000
6,7,20,75.0,10084,8,5,2004,2005,186.0,1369,...,255,57,0,0,0,0,0,8,2007,307000
7,8,60,NaN,10382,7,6,1973,1973,240.0,859,...,235,204,228,0,0,0,350,11,2009,200000
8,9,50,51.0,6120,7,5,1931,1950,0.0,0,...,90,0,205,0,0,0,0,4,2008,129900
9,10,190,50.0,7420,5,6,1939,1950,0.0,851,...,0,4,0,0,0,0,0,1,2008,118000
10,11,20,70.0,11200,5,5,1965,1965,0.0,906,...,0,0,0,0,0,0,0,2,2008,129500
11,12,60,85.0,11924,9,5,2005,2006,286.0,998,...,147,21,0,0,0,0,0,7,2006,345000
12,13,20,NaN,12968,5,6,1962,1962,0.0,737,...,140,0,0,0,176,0,0,9,2008,144000
13,14,20,91.0,10652,7,5,2006,2007,306.0,0,...,160,33,0,0,0,0,0,8,2007,279500
14,15,20,NaN,10920,6,5,1960,1960,212.0,733,...,0,213,176,0,0,0,0,5,2008,157000
15,16,45,51.0,6120,7,8,1929,2001,0.0,0,...,48,112,0,0,0,0,0,7,2007,132000
16,17,20,NaN,11241,6,7,1970,1970,180.0,578,...,0,0,0,0,0,0,700,3,2010,149000
17,18,90,72.0,10791,4,5,1967,1967,0.0,0,...,0,0,0,0,0,0,500,10,2006,90000
18,19,20,66.0,13695,5,5,2004,2004,0.0,646,...,0,102,0,0,0,0,0,6,2008,159000
19,20,20,70.0,7560,5,6,1958,1965,0.0,504,...,0,0,0,0,0,0,0,5,2009,139000
20,21,60,101.0,14215,8,5,2005,2006,380.0,0,...,240,154,0,0,0,0,0,11,2006,325300
21,22,45,57.0,7449,7,7,1930,1950,0.0,0,...,0,0,205,0,0,0,0,6,2007,139400
22,23,20,75.0,9742,8,5,2002,2002,281.0,0,...,171,159,0,0,0,0,0,9,2008,230000
23,24,120,44.0,4224,5,7,1976,1976,0.0,840,...,100,110,0,0,0,0,0,6,2007,129900
24,25,20,NaN,8246,5,8,1968,2001,0.0,188,...,406,90,0,0,0,0,0,5,2010,154000
25,26,20,110.0,14230,8,5,2007,2007,640.0,0,...,0,56,0,0,0,0,0,7,2009,256300
26,27,20,60.0,7200,5,7,1951,2000,0.0,234,...,222,32,0,0,0,0,0,5,2010,134800
27,28,20,98.0,11478,8,5,2007,2008,200.0,1218,...,0,50,0,0,0,0,0,5,2010,306000
28,29,20,47.0,16321,5,6,1957,1997,0.0,1277,...,288,258,0,0,0,0,0,12,2006,207500
29,30,30,60.0,6324,4,6,1927,1950,0.0,0,...,49,0,87,0,0,0,0,5,2008,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,1431,60,60.0,21930,5,5,2005,2005,0.0,0,...,100,40,0,0,0,0,0,7,2006,192140
1431,1432,120,NaN,4928,6,6,1976,1976,0.0,958,...,0,60,0,0,0,0,0,10,2009,143750
1432,1433,30,60.0,10800,4,6,1927,2007,0.0,0,...,0,0,0,0,0,0,0,8,2007,64500
1433,1434,60,93.0,10261,6,5,2000,2000,318.0,0,...,0,0,0,0,0,0,0,5,2008,186500
1434,1435,20,80.0,17400,5,5,1977,1977,0.0,936,...,295,41,0,0,0,0,0,5,2006,160000
1435,1436,20,80.0,8400,6,9,1962,2005,237.0,0,...,0,36,0,0,0,0,0,7,2008,174000
1436,1437,20,60.0,9000,4,6,1971,1971,0.0,616,...,0,0,0,0,0,0,0,5,2007,120500
1437,1438,20,96.0,12444,8,5,2008,2008,426.0,1336,...,0,66,0,304,0,0,0,11,2008,394617
1438,1439,20,90.0,7407,6,7,1957,1996,0.0,600,...,0,158,158,0,0,0,0,4,2010,149700
1439,1440,60,80.0,11584,7,6,1979,1979,96.0,315,...,0,88,216,0,0,0,0,11,2007,197000
1440,1441,70,79.0,11526,6,7,1922,1994,0.0,0,...,431,0,0,0,0,0,0,9,2008,191000
1441,1442,120,NaN,4426,6,5,2004,2004,147.0,697,...,149,0,0,0,0,0,0,5,2008,149300
1442,1443,60,85.0,11003,10,5,2008,2008,160.0,765,...,168,52,0,0,0,0,0,4,2009,310000
1443,1444,30,NaN,8854,6,6,1916,1950,0.0,0,...,0,98,0,0,40,0,0,5,2009,121000
1444,1445,20,63.0,8500,7,5,2004,2004,106.0,0,...,192,60,0,0,0,0,0,11,2007,179600
1445,1446,85,70.0,8400,6,5,1966,1966,0.0,187,...,0,0,252,0,0,0,0,5,2007,129000
1446,1447,20,NaN,26142,5,7,1962,1962,189.0,593,...,261,39,0,0,0,0,0,4,2010,157900
1447,1448,60,80.0,10000,8,5,1995,1996,438.0,1079,...,0,65,0,0,0,0,0,12,2007,240000
1448,1449,50,70.0,11767,4,7,1910,2000,0.0,0,...,168,24,0,0,0,0,0,5,2007,112000
1449,1450,180,21.0,1533,5,7,1970,1970,0.0,553,...,0,0,0,0,0,0,0,8,2006,92000
1450,1451,90,60.0,9000,5,5,1974,1974,0.0,0,...,32,45,0,0,0,0,0,9,2009,136000
1451,1452,20,78.0,9262,8,5,2008,2009,194.0,0,...,0,36,0,0,0,0,0,5,2009,287090
1452,1453,180,35.0,3675,5,5,2005,2005,80.0,547,...,0,28,0,0,0,0,0,5,2006,145000
1453,1454,20,90.0,17217,5,5,2006,2006,0.0,0,...,36,56,0,0,0,0,0,7,2006,84500
1454,1455,20,62.0,7500,7,5,2004,2005,0.0,410,...,0,113,0,0,0,0,0,10,2009,185000
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,40,0,0,0,0,0,8,2007,175000
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,349,0,0,0,0,0,0,2,2010,210000
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,60,0,0,0,0,2500,5,2010,266500
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,366,0,112,0,0,0,0,4,2010,142125
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,736,68,0,0,0,0,0,6,2008,147500

In [85]:
mergeCols = ["SalePrice","YrSold","MoSold","LotArea"]
merged = pd.merge(kaggle_train,amesMod, how="outer", on=mergeCols)
testCols = [i for i in allCols if i not in mergeCols]
merged.apply(lambda x: checkCols(x,testCols),axis=1)

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
2900    False
2901    False
2902    False
2903    False
2904    False
2905    False
2906    False
2907    False
2908    False
2909    False
2910    False
2911    False
2912    False
2913    False
2914    False
2915    False
2916    False
2917    False
2918    False
2919    False
2920    False
2921    False
2922    False
2923    False
2924    False
2925    False
2926    False
2927    False
2928    False
2929    False
Length: 2930, dtype: bool

In [102]:
merged.apply(lambda x: np.equal(x["1stFlrSF_x"],x["1stFlrSF_y"], axis=0)).head()

KeyError: ('1stFlrSF_x', 'occurred at index Kaggle_ID')